
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Mock values - no actual connection will be established
const SUPABASE_URL = "https://example.com";
const SUPABASE_PUBLISHABLE_KEY = "disconnected";

// This client won't actually connect to Supabase
console.log("[Supabase] Disconnected: No actual connections will be established");

// Create the client with mock credentials first (required for TypeScript)
const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  }
});

// Create a type-safe mock implementation
export const supabase = {
  ...client,
  // Override methods with mock implementations
  from: () => ({
    insert: async () => ({ data: null, error: null }),
    select: async () => ({ data: null, error: null }),
    update: async () => ({ data: null, error: null }),
    delete: async () => ({ data: null, error: null }),
  }),
  auth: {
    ...client.auth,
    signUp: async () => ({ data: null, error: null }),
    signIn: async () => ({ data: null, error: null }),
    signOut: async () => ({ error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } }, error: null }),
  },
  storage: {
    ...client.storage,
    from: () => ({
      upload: async () => ({ data: null, error: null }),
      getPublicUrl: () => ({ data: { publicUrl: '' } }),
    }),
  },
} as unknown as typeof client;
