// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceodkbrkttghwrpfcsbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlb2RrYnJrdHRnaHdycGZjc2JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzgwOTYsImV4cCI6MjA2MDQ1NDA5Nn0.9r9DaaTVmKPDLk0iRjc3rCWRAn4W6eTa8g5wI4NJONE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);